services:
  reverse-proxy:
    image: io-manager-proxy
    container_name: io-manager-proxy
    build:
      context: .
      dockerfile: ./services/proxy/Dockerfile.local
      args:
        BUILD_ENV: dev
    ports:
      - '8080:8080'
      - '443:443'
    depends_on:
      - server
      - admin
  mongodb:
    container_name: io-manager-mongo
    image: 'mongo'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: interop42
      MONGO_INITDB_ROOT_PASSWORD: verysecret
    command: --quiet
  server:
    container_name: io-manager-server
    image: io-manager-server
    build:
      context: .
      dockerfile: ./services/server/Dockerfile.local
    # volumes:
    #   - ./logs:/home/node/app/logs
    depends_on:
      - mongodb
    environment:
      API_NAME: 'ioManager'
      API_PORT: '4356'
      API_STORE_MONGO: mongodb://interop42:verysecret@mongodb:27017/g42-home?authSource=admin
      API_TOKEN_SECRET: <YOUR_SECRET>
      API_LICENSE_KEY: <YOUR_LICENSE_KEY_GOES_HERE>
  admin:
    container_name: io-manager-admin
    image: io-manager-admin
    build:
      context: .
      dockerfile: ./services/admin/Dockerfile.local
volumes:
  mongodb_data:
  mongodb_config:
